export {default as Image1} from './1.png'
export {default as Image2} from './2.png'
export {default as Image3} from './3.png'
export {default as Image4} from './4.png'
export {default as Image5} from './5.png'
export {default as Image6} from './6.png'
export {default as Image7} from './7.png'